
version: '3'

services:

  app:
    build:
      context: ./node
    image: vweisscobos/node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    container_name: app
    networks:
      - app
    depends_on:
      - db

  db:
    build:
      context: ./db
    image: vweisscobos/db
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app

  nginx:
    build:
      context: ./nginx
    image: vweisscobos/nginx
    container_name: nginx
    networks:
      - app
    ports:
      - "8080:80"


networks:
  app:
    driver: "bridge"